databases:
  - name: postgres
    ipAllowList: []
    databaseName: ruby_sample_app
    user: ruby_sample_app_user

services:
  - type: web
    name: ruby-sample-app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false